id: P005479
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24934
  title: གངས་རིན་པོ་ཆེའི་གཏེར་མཛོད།
  author: ''
  volumes:
    001ec9fa1ef343798be29a7a44f5c190:
      image_group_id: I1KG24936
      title: ''
      volume_number: 1
      total_pages: 536
